In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import pandas as pd
from sklearn.cluster import AgglomerativeClustering
import seaborn as sns

In [2]:
X = pd.read_csv('./data.csv')
X.isnull().sum().sort_values(ascending=False)

symptom6      1084
symptom5      1082
symptom4      1066
symptom3      1012
symptom2       924
symptom1       815
hosp_vis       636
sym_on         636
age            242
gender         183
from_wuhan       4
vis_wuhan        0
death            0
recov            0
country          0
location         0
id               0
dtype: int64

In [3]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1085 entries, 0 to 1084
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          1085 non-null   int64
 1   location    1085 non-null   object
 2   country     1085 non-null   object
 3   gender      902 non-null    object
 4   age         843 non-null    float64
 5   sym_on      449 non-null    object
 6   hosp_vis    449 non-null    object
 7   vis_wuhan   1085 non-null   int64
 8   from_wuhan  1081 non-null   float64
 9   death       1085 non-null   int64
 10  recov       1085 non-null   int64
 11  symptom1    270 non-null    object
 12  symptom2    161 non-null    object
 13  symptom3    73 non-null     object
 14  symptom4    19 non-null     object
 15  symptom5    3 non-null      object
 16  symptom6    1 non-null      object
dtypes: float64(2), int64(4), object(11)
memory usage: 144.2+ KB

In [4]:
#X.info()
#X.head
X['symptom6'].fillna("Unknown", inplace=True)
X['symptom5'].fillna("Unknown", inplace=True)
X['symptom4'].fillna("Unknown", inplace=True)
X['symptom3'].fillna("Unknown", inplace=True)
X['symptom2'].fillna("Unknown", inplace=True)
X['symptom1'].fillna("Unknown", inplace=True)
X['hosp_vis'].fillna("Unknown", inplace=True)
X['sym_on'].fillna("Unknown", inplace=True)
X['gender'].fillna("Unknown", inplace=True)
X.dropna(subset=["age"], inplace=True)
X.dropna(subset=["from_wuhan"], inplace=True)
print(X.dtypes)
X.info()
X.head()

id              int64
location       object
country        object
gender         object
age           float64
sym_on         object
hosp_vis       object
vis_wuhan       int64
from_wuhan    float64
death           int64
recov           int64
symptom1       object
symptom2       object
symptom3       object
symptom4       object
symptom5       object
symptom6       object
dtype: object
<class 'pandas.core.frame.DataFrame'>
Int64Index: 839 entries, 0 to 1084
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          839 non-null    int64
 1   location    839 non-null    object
 2   country     839 non-null    object
 3   gender      839 non-null    object
 4   age         839 non-null    float64
 5   sym_on      839 non-null    object
 6   hosp_vis    839 non-null    object
 7   vis_wuhan   839 non-null    int64
 8   from_wuhan  839 non-null    float64
 9   death       839 non-null    int64
 10  recov       839 non-null    int64
 11  symptom1    839 non-null    object
 12  symptom2    839 non-null    object
 13  symptom3    839 non-null    object
 14  symptom4    839 non-null    object
 15  symptom5    839 non-null    object
 16  symptom6    839 non-null    object
dtypes: float64(2), int64(4), object(11)
memory usage: 118.0+ KB

,id,location,country,gender,age,sym_on,hosp_vis,vis_wuhan,from_wuhan,death,recov,symptom1,symptom2,symptom3,symptom4,symptom5,symptom6
0,1,"Shenzhen, Guangdong",China,male,66.0,1/3/2020,1/11/2020,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,2,Shanghai,China,female,56.0,1/15/2020,1/15/2020,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,3,Zhejiang,China,male,46.0,1/4/2020,1/17/2020,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,4,Tianjin,China,female,60.0,Unknown,Unknown,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,5,Tianjin,China,male,58.0,Unknown,Unknown,0,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [5]:
X.insert(0,"status",X['death']) #第一個參數是插入的index位置
#X['status'] = X['status'].astype(str) 
#X['status'] = X['status'].replace(0,3)
X.head()

,status,id,location,country,gender,age,sym_on,hosp_vis,vis_wuhan,from_wuhan,death,recov,symptom1,symptom2,symptom3,symptom4,symptom5,symptom6
0,0,1,"Shenzhen, Guangdong",China,male,66.0,1/3/2020,1/11/2020,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,0,2,Shanghai,China,female,56.0,1/15/2020,1/15/2020,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,0,3,Zhejiang,China,male,46.0,1/4/2020,1/17/2020,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,0,4,Tianjin,China,female,60.0,Unknown,Unknown,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,0,5,Tianjin,China,male,58.0,Unknown,Unknown,0,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [6]:
newX = X
newX['age'].values[X['age'].values < 18] = 3 #young
newX['age'].values[X['age'].values > 65] = 2 #old
newX['age'].values[X['age'].values > 18] = 1 #general

newX['age'] = newX['age'].map({1:'general', 2:'old',3:'young'})

In [7]:
#X['status'] = X['status'].replace(to_replace = 3, value = 1)
X.head()

,status,id,location,country,gender,age,sym_on,hosp_vis,vis_wuhan,from_wuhan,death,recov,symptom1,symptom2,symptom3,symptom4,symptom5,symptom6
0,0,1,"Shenzhen, Guangdong",China,male,old,1/3/2020,1/11/2020,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,0,2,Shanghai,China,female,general,1/15/2020,1/15/2020,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,0,3,Zhejiang,China,male,general,1/4/2020,1/17/2020,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,0,4,Tianjin,China,female,general,Unknown,Unknown,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,0,5,Tianjin,China,male,general,Unknown,Unknown,0,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [8]:
X.isnull().sum().sort_values(ascending=False)

age           3
symptom6      0
symptom5      0
id            0
location      0
country       0
gender        0
sym_on        0
hosp_vis      0
vis_wuhan     0
from_wuhan    0
death         0
recov         0
symptom1      0
symptom2      0
symptom3      0
symptom4      0
status        0
dtype: int64

In [9]:
X.head()

,status,id,location,country,gender,age,sym_on,hosp_vis,vis_wuhan,from_wuhan,death,recov,symptom1,symptom2,symptom3,symptom4,symptom5,symptom6
0,0,1,"Shenzhen, Guangdong",China,male,old,1/3/2020,1/11/2020,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,0,2,Shanghai,China,female,general,1/15/2020,1/15/2020,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,0,3,Zhejiang,China,male,general,1/4/2020,1/17/2020,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,0,4,Tianjin,China,female,general,Unknown,Unknown,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,0,5,Tianjin,China,male,general,Unknown,Unknown,0,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [10]:
X.loc[:,'sym_on']=pd.to_datetime(X.loc[:,'sym_on'],
                                           format='%m/%d/%Y',errors='coerce')
X.loc[:,'sym_on']=pd.to_datetime(X.loc[:,'sym_on'],
                                           format='%d/%m/%Y', errors='coerce')
X.loc[:,'hosp_vis']=pd.to_datetime(X.loc[:,'hosp_vis'],
                                           format='%m/%d/%Y',errors='coerce')

In [11]:
X['hosp_vis'] = (X['hosp_vis'] - X['sym_on']).dt.days
X.insert(5,"hosp_vis—sym_on",X['hosp_vis'])
#X =X.reset_index(drop=True)
X.head()

,status,id,location,country,gender,hosp_vis—sym_on,age,sym_on,hosp_vis,vis_wuhan,from_wuhan,death,recov,symptom1,symptom2,symptom3,symptom4,symptom5,symptom6
0,0,1,"Shenzhen, Guangdong",China,male,8.0,old,2020-01-03,8.0,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
1,0,2,Shanghai,China,female,0.0,general,2020-01-15,0.0,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
2,0,3,Zhejiang,China,male,13.0,general,2020-01-04,13.0,0,1.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
3,0,4,Tianjin,China,female,NaN,general,NaT,NaN,1,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown
4,0,5,Tianjin,China,male,NaN,general,NaT,NaN,0,0.0,0,0,Unknown,Unknown,Unknown,Unknown,Unknown,Unknown

In [12]:
newX = X.drop(labels=["id","sym_on","hosp_vis","symptom1","symptom2","symptom3","symptom4","symptom5","symptom6",],axis = "columns")
newX.head()

,status,location,country,gender,hosp_vis—sym_on,age,vis_wuhan,from_wuhan,death,recov
0,0,"Shenzhen, Guangdong",China,male,8.0,old,1,0.0,0,0
1,0,Shanghai,China,female,0.0,general,0,1.0,0,0
2,0,Zhejiang,China,male,13.0,general,0,1.0,0,0
3,0,Tianjin,China,female,NaN,general,1,0.0,0,0
4,0,Tianjin,China,male,NaN,general,0,0.0,0,0

In [13]:
newX['hosp_vis—sym_on'].values[X['hosp_vis—sym_on'].values < 3] = 3 #short
newX['hosp_vis—sym_on'].values[X['hosp_vis—sym_on'].values > 10] = 2 #long
newX['hosp_vis—sym_on'].values[X['hosp_vis—sym_on'].values > 3] = 1 #soso

newX['hosp_vis—sym_on'] = newX['hosp_vis—sym_on'].map({1:'soso', 2:'long',3:'short'})

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in less
  """Entry point for launching an IPython kernel.
C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater

C:\Users\User\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in greater
  This is separate from the ipykernel package so we can avoid doing imports until

In [14]:
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame(newX)
newX = pd.get_dummies(df)

In [15]:
newX.head()

,status,vis_wuhan,from_wuhan,death,recov,location_Afghanistan,location_Aichi Prefecture,location_Amiens,location_Andalusia,location_Annecy,...,country_USA,country_Vietnam,gender_Unknown,gender_female,gender_male,hosp_vis—sym_on_short,hosp_vis—sym_on_soso,age_general,age_old,age_young
0,0,1,0.0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,1,0
1,0,0,1.0,0,0,0,0,0,0,0,...,0,0,0,1,0,1,0,1,0,0
2,0,0,1.0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,1,0,0
3,0,1,0.0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,1,0,0
4,0,0,0.0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,1,0,0

In [16]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
frequent_itemsets = apriori(newX, min_support=0.05, use_colnames=True)
#rules = association_rules(frequent_itemsets,metric = 'leverage',min_threshold = 0.15)

In [17]:
pd.set_option('max_colwidth',200)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x:len(x))
frequent_itemsets

,support,itemsets,length
0,0.069130,(status),1
1,0.175209,(vis_wuhan),1
2,0.181168,(from_wuhan),1
3,0.069130,(death),1
4,0.172825,(recov),1
...,...,...,...
121,0.064362,"(country_Singapore, age_general, location_Singapore, recov)",4
122,0.058403,"(country_Singapore, age_general, location_Singapore, gender_male)",4
123,0.064362,"(hosp_vis—sym_on_short, country_Singapore, age_general, location_Singapore)",4
124,0.050060,"(location_South Korea, age_general, country_South Korea, gender_female)",4
125,0.065554,"(country_Japan, hosp_vis—sym_on_short, age_general, gender_male)",4

In [24]:
pd.set_option('display.max_rows', None)
frequent_itemsets[ (frequent_itemsets['length'] >2) 
                  & (frequent_itemsets [ 'support' ] < 0.2) ]

,support,itemsets,length
82,0.052443,"(gender_male, death, status)",3
83,0.063170,"(country_China, vis_wuhan, gender_male)",3
84,0.082241,"(country_China, vis_wuhan, age_general)",3
85,0.054827,"(vis_wuhan, age_general, gender_female)",3
86,0.101311,"(vis_wuhan, age_general, gender_male)",3
87,0.058403,"(hosp_vis—sym_on_short, vis_wuhan, age_general)",3
88,0.056019,"(country_China, from_wuhan, gender_male)",3
89,0.058403,"(country_China, from_wuhan, age_general)",3
90,0.060787,"(age_general, from_wuhan, gender_female)",3
91,0.064362,"(from_wuhan, age_general, gender_male)",3
92,0.070322,"(country_Singapore, location_Singapore, recov)",3
93,0.064362,"(age_general, location_Singapore, recov)",3
94,0.064362,"(country_Singapore, age_general, recov)",3
95,0.064362,"(age_general, gender_female, recov)",3
96,0.078665,"(recov, age_general, gender_male)",3
97,0.066746,"(hosp_vis—sym_on_short, age_general, recov)",3
98,0.060787,"(location_Hong Kong, country_Hong Kong, age_general)",3
99,0.063170,"(country_Singapore, location_Singapore, gender_male)",3
100,0.067938,"(hosp_vis—sym_on_short, country_Singapore, location_Singapore)",3
101,0.096544,"(country_Singapore, age_general, location_Singapore)",3
102,0.058403,"(age_general, location_Singapore, gender_male)",3
103,0.064362,"(hosp_vis—sym_on_short, age_general, location_Singapore)",3
104,0.057211,"(location_South Korea, gender_female, country_South Korea)",3
105,0.050060,"(location_South Korea, country_South Korea, gender_male)",3
106,0.091776,"(location_South Korea, age_general, country_South Korea)",3
107,0.050060,"(location_South Korea, age_general, gender_female)",3
108,0.060787,"(country_China, age_general, gender_female)",3
109,0.103695,"(country_China, age_general, gender_male)",3
110,0.058403,"(country_Japan, age_general, gender_female)",3
111,0.083433,"(country_Japan, hosp_vis—sym_on_short, gender_male)",3
112,0.106079,"(country_Japan, age_general, gender_male)",3
113,0.098927,"(country_Japan, hosp_vis—sym_on_short, age_general)",3
114,0.058403,"(country_Singapore, age_general, gender_male)",3
115,0.064362,"(hosp_vis—sym_on_short, country_Singapore, age_general)",3
116,0.051251,"(age_general, country_South Korea, gender_female)",3
117,0.109654,"(hosp_vis—sym_on_short, age_general, gender_female)",3
118,0.177592,"(hosp_vis—sym_on_short, age_general, gender_male)",3
119,0.065554,"(hosp_vis—sym_on_soso, age_general, gender_male)",3
120,0.058403,"(country_China, vis_wuhan, age_general, gender_male)",4
121,0.064362,"(country_Singapore, age_general, location_Singapore, recov)",4
122,0.058403,"(country_Singapore, age_general, location_Singapore, gender_male)",4
123,0.064362,"(hosp_vis—sym_on_short, country_Singapore, age_general, location_Singapore)",4
124,0.050060,"(location_South Korea, age_general, country_South Korea, gender_female)",4
125,0.065554,"(country_Japan, hosp_vis—sym_on_short, age_general, gender_male)",4

In [30]:
pd.set_option('display.max_rows', None)
from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.01, support_only=False)
rules[ (rules['conviction'] >= 0) &
    (rules['confidence' ] < 0.5) ]
#    (rules['lift']> 1.2) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
2,(gender_male),(status),0.564958,0.069130,0.052443,0.092827,1.342791,0.013388,1.026122
4,(country_China),(vis_wuhan),0.221692,0.175209,0.091776,0.413978,2.362775,0.052933,1.407442
6,(vis_wuhan),(gender_female),0.175209,0.413588,0.064362,0.367347,0.888196,-0.008102,0.926910
7,(gender_female),(vis_wuhan),0.413588,0.175209,0.064362,0.155620,0.888196,-0.008102,0.976801
9,(gender_male),(vis_wuhan),0.564958,0.175209,0.109654,0.194093,1.107782,0.010669,1.023432
10,(hosp_vis—sym_on_short),(vis_wuhan),0.359952,0.175209,0.066746,0.185430,1.058341,0.003679,1.012549
11,(vis_wuhan),(hosp_vis—sym_on_short),0.175209,0.359952,0.066746,0.380952,1.058341,0.003679,1.033923
13,(age_general),(vis_wuhan),0.781883,0.175209,0.156138,0.199695,1.139757,0.019146,1.030597
14,(country_China),(from_wuhan),0.221692,0.181168,0.097735,0.440860,2.433432,0.057572,1.464449
16,(from_wuhan),(gender_female),0.181168,0.413588,0.082241,0.453947,1.097585,0.007312,1.073912
17,(gender_female),(from_wuhan),0.413588,0.181168,0.082241,0.198847,1.097585,0.007312,1.022067
19,(gender_male),(from_wuhan),0.564958,0.181168,0.096544,0.170886,0.943246,-0.005809,0.987599
20,(hosp_vis—sym_on_short),(from_wuhan),0.359952,0.181168,0.061979,0.172185,0.950418,-0.003233,0.989149
21,(from_wuhan),(hosp_vis—sym_on_short),0.181168,0.359952,0.061979,0.342105,0.950418,-0.003233,0.972872
23,(age_general),(from_wuhan),0.781883,0.181168,0.126341,0.161585,0.891909,-0.015311,0.976643
25,(gender_male),(death),0.564958,0.069130,0.052443,0.092827,1.342791,0.013388,1.026122
27,(recov),(location_Singapore),0.172825,0.107271,0.070322,0.406897,3.793180,0.051783,1.505183
29,(recov),(country_Singapore),0.172825,0.107271,0.070322,0.406897,3.793180,0.051783,1.505183
30,(gender_female),(recov),0.413588,0.172825,0.076281,0.184438,1.067197,0.004803,1.014240
31,(recov),(gender_female),0.172825,0.413588,0.076281,0.441379,1.067197,0.004803,1.049751
33,(gender_male),(recov),0.564958,0.172825,0.094160,0.166667,0.964368,-0.003479,0.992610
34,(hosp_vis—sym_on_short),(recov),0.359952,0.172825,0.076281,0.211921,1.226216,0.014073,1.049609
35,(recov),(hosp_vis—sym_on_short),0.172825,0.359952,0.076281,0.441379,1.226216,0.014073,1.145764
36,(age_general),(recov),0.781883,0.172825,0.143027,0.182927,1.058452,0.007899,1.012364
38,(country_Japan),(location_Hokkaido),0.221692,0.056019,0.056019,0.252688,4.510753,0.043600,1.263169
43,(age_general),(location_Hong Kong),0.781883,0.094160,0.060787,0.077744,0.825660,-0.012835,0.982200
47,(gender_male),(location_Singapore),0.564958,0.107271,0.063170,0.111814,1.042358,0.002567,1.005116
48,(hosp_vis—sym_on_short),(location_Singapore),0.359952,0.107271,0.067938,0.188742,1.759492,0.029326,1.100426
50,(age_general),(location_Singapore),0.781883,0.107271,0.096544,0.123476,1.151067,0.012670,1.018488
55,(gender_female),(location_South Korea),0.413588,0.107271,0.057211,0.138329,1.289529,0.012845,1.036044
56,(location_South Korea),(gender_male),0.107271,0.564958,0.050060,0.466667,0.826020,-0.010544,0.815703
57,(gender_male),(location_South Korea),0.564958,0.107271,0.050060,0.088608,0.826020,-0.010544,0.979523
59,(age_general),(location_South Korea),0.781883,0.107271,0.091776,0.117378,1.094224,0.007903,1.011452
60,(country_China),(gender_female),0.221692,0.413588,0.083433,0.376344,0.909950,-0.008257,0.940282
61,(gender_female),(country_China),0.413588,0.221692,0.083433,0.201729,0.909950,-0.008257,0.974992
63,(gender_male),(country_China),0.564958,0.221692,0.138260,0.244726,1.103897,0.013013,1.030497
64,(hosp_vis—sym_on_short),(country_China),0.359952,0.221692,0.059595,0.165563,0.746813,-0.020204,0.932734
65,(country_China),(hosp_vis—sym_on_short),0.221692,0.359952,0.059595,0.268817,0.746813,-0.020204,0.875359
66,(hosp_vis—sym_on_soso),(country_China),0.156138,0.221692,0.064362,0.412214,1.859394,0.029748,1.324134
67,(country_China),(hosp_vis—sym_on_soso),0.221692,0.156138,0.064362,0.290323,1.859394,0.029748,1.189078
69,(age_general),(country_China),0.781883,0.221692,0.164482,0.210366,0.948908,-0.008856,0.985656
70,(country_China),(age_old),0.221692,0.184744,0.051251,0.231183,1.251370,0.010295,1.060403
71,(age_old),(country_China),0.184744,0.221692,0.051251,0.277419,1.251370,0.010295,1.077122
72,(country_Hong Kong),(gender_female),0.110846,0.413588,0.054827,0.494624,1.195934,0.008983,1.160348
73,(gender_female),(country_Hong Kong),0.413588,0.110846,0.054827,0.132565,1.195934,0.008983,1.025038
75,(gender_male),(country_Hong Kong),0.564958,0.110846,0.056019,0.099156,0.894537,-0.006604,0.987023
76,(hosp_vis—sym_on_short),(country_Hong Kong),0.359952,0.110846,0.056019,0.155629,1.404009,0.016120,1.053037
79,(age_general),(country_Hong Kong),0.781883,0.110846,0.073897,0.094512,0.852642,-0.012771,0.981961
80,(country_Japan),(gender_female),0.221692,0.413588,0.076281,0.344086,0.831954,-0.015408,0.894039
81,(gender_female),(country_Japan),0.413588,0.221692,0.076281,0.184438,0.831954,-0.015408,0.954321
83,(gender_male),(country_Japan),0.564958,0.221692,0.144219,0.255274,1.151479,0.018972,1.045093
85,(hosp_vis—sym_on_short),(country_Japan),0.359952,0.221692,0.127533,0.354305,1.598181,0.047734,1.205379
87,(age_general),(country_Japan),0.781883,0.221692,0.164482,0.210366,0.948908,-0.008856,0.985656
88,(country_Japan),(age_old),0.221692,0.184744,0.050060,0.225806,1.222268,0.009103,1.053039
89,(age_old),(country_Japan),0.184744,0.221692,0.050060,0.270968,1.222268,0.009103,1.067590
91,(gender_male),(country_Singapore),0.564958,0.107271,0.063170,0.111814,1.042358,0.002567,1.005116
92,(hosp_vis—sym_on_short),(country_Singapore),0.359952,0.107271,0.067938,0.188742,1.759492,0.029326,1.100426
95,(age_general),(country_Singapore),0.781883,0.107271,0.096544,0.123476,1.151067,0.012670,1.018488
96,(gender_female),(country_South Korea),0.413588,0.109654,0.058403,0.141210,1.287777,0.013051,1.036745
98,(country_South Korea),(gender_male),0.109654,0.564958,0.051251,0.467391,0.827302,-0.010699,0.816813
99,(gender_male),(country_South Korea),0.564958,0.109654,0.051251,0.090717,0.827302,-0.010699,0.979174
100,(age_general),(country_South Korea),0.781883,0.109654,0.094160,0.120427,1.098240,0.008423,1.012247
102,(hosp_vis—sym_on_short),(gender_female),0.359952,0.413588,0.139452,0.387417,0.936723,-0.009420,0.957279
103,(gender_female),(hosp_vis—sym_on_short),0.413588,0.359952,0.139452,0.337176,0.936723,-0.009420,0.965637
104,(hosp_vis—sym_on_soso),(gender_female),0.156138,0.413588,0.060787,0.389313,0.941307,-0.003790,0.960250
105,(gender_female),(hosp_vis—sym_on_soso),0.413588,0.156138,0.060787,0.146974,0.941307,-0.003790,0.989257
106,(age_general),(gender_female),0.781883,0.413588,0.327771,0.419207,1.013588,0.004394,1.009676
108,(age_old),(gender_female),0.184744,0.413588,0.076281,0.412903,0.998345,-0.000126,0.998834
109,(gender_female),(age_old),0.413588,0.184744,0.076281,0.184438,0.998345,-0.000126,0.999625
111,(gender_male),(hosp_vis—sym_on_short),0.564958,0.359952,0.220501,0.390295,1.084297,0.017143,1.049767
113,(gender_male),(hosp_vis—sym_on_soso),0.564958,0.156138,0.095352,0.168776,1.080942,0.007140,1.015204
117,(gender_male),(age_old),0.564958,0.184744,0.104887,0.185654,1.004927,0.000514,1.001118
119,(age_general),(hosp_vis—sym_on_short),0.781883,0.359952,0.287247,0.367378,1.020630,0.005806,1.011738
120,(hosp_vis—sym_on_short),(age_old),0.359952,0.184744,0.061979,0.172185,0.932023,-0.004520,0.984830
121,(age_old),(hosp_vis—sym_on_short),0.184744,0.359952,0.061979,0.335484,0.932023,-0.004520,0.963179
123,(age_general),(hosp_vis—sym_on_soso),0.781883,0.156138,0.107271,0.137195,0.878677,-0.014811,0.978045
127,(gender_male),"(death, status)",0.564958,0.069130,0.052443,0.092827,1.342791,0.013388,1.026122
131,"(country_China, gender_male)",(vis_wuhan),0.138260,0.175209,0.063170,0.456897,2.607729,0.038946,1.518664
133,(country_China),"(vis_wuhan, gender_male)",0.221692,0.109654,0.063170,0.284946,2.598586,0.038861,1.245145
134,(vis_wuhan),"(country_China, gender_male)",0.175209,0.138260,0.063170,0.360544,2.607729,0.038946,1.347615
135,(gender_male),"(country_China, vis_wuhan)",0.564958,0.091776,0.063170,0.111814,1.218341,0.011321,1.022561
139,(country_China),"(vis_wuhan, age_general)",0.221692,0.156138,0.082241,0.370968,2.375893,0.047626,1.341524
140,(vis_wuhan),"(country_China, age_general)",0.175209,0.164482,0.082241,0.469388,2.853741,0.053422,1.574631
141,(age_general),"(country_China, vis_wuhan)",0.781883,0.091776,0.082241,0.105183,1.146084,0.010483,1.014983
142,"(vis_wuhan, age_general)",(gender_female),0.156138,0.413588,0.054827,0.351145,0.849022,-0.009750,0.903765
144,"(age_general, gender_female)",(vis_wuhan),0.327771,0.175209,0.054827,0.167273,0.954706,-0.002601,0.990470
145,(vis_wuhan),"(age_general, gender_female)",0.175209,0.327771,0.054827,0.312925,0.954706,-0.002601,0.978392
146,(age_general),"(vis_wuhan, gender_female)",0.781883,0.064362,0.054827,0.070122,1.089487,0.004503,1.006194
147,(gender_female),"(vis_wuhan, age_general)",0.413588,0.156138,0.054827,0.132565,0.849022,-0.009750,0.972824
150,"(age_general, gender_male)",(vis_wuhan),0.442193,0.175209,0.101311,0.229111,1.307644,0.023835,1.069922
152,(age_general),"(vis_wuhan, gender_male)",0.781883,0.109654,0.101311,0.129573,1.181651,0.015574,1.022884
153,(gender_male),"(vis_wuhan, age_general)",0.564958,0.156138,0.101311,0.179325,1.148501,0.013099,1.028253
155,"(hosp_vis—sym_on_short, age_general)",(vis_wuhan),0.287247,0.175209,0.058403,0.203320,1.160443,0.008075,1.035285
156,"(vis_wuhan, age_general)",(hosp_vis—sym_on_short),0.156138,0.359952,0.058403,0.374046,1.039154,0.002201,1.022515
157,(hosp_vis—sym_on_short),"(vis_wuhan, age_general)",0.359952,0.156138,0.058403,0.162252,1.039154,0.002201,1.007297
158,(vis_wuhan),"(hosp_vis—sym_on_short, age_general)",0.175209,0.287247,0.058403,0.333333,1.160443,0.008075,1.069130
159,(age_general),"(hosp_vis—sym_on_short, vis_wuhan)",0.781883,0.066746,0.058403,0.074695,1.119093,0.006215,1.008591
161,"(country_China, gender_male)",(from_wuhan),0.138260,0.181168,0.056019,0.405172,2.236445,0.030971,1.376587
163,(country_China),"(from_wuhan, gender_male)",0.221692,0.096544,0.056019,0.252688,2.617350,0.034616,1.208942
164,(from_wuhan),"(country_China, gender_male)",0.181168,0.138260,0.056019,0.309211,2.236445,0.030971,1.247471
165,(gender_male),"(country_China, from_wuhan)",0.564958,0.097735,0.056019,0.099156,1.014536,0.000803,1.001577
167,"(country_China, age_general)",(from_wuhan),0.164482,0.181168,0.058403,0.355072,1.959907,0.028604,1.269650
168,"(from_wuhan, age_general)",(country_China),0.126341,0.221692,0.058403,0.462264,2.085159,0.030394,1.447379
169,(country_China),"(from_wuhan, age_general)",0.221692,0.126341,0.058403,0.263441,2.085159,0.030394,1.186136
170,(from_wuhan),"(country_China, age_general)",0.181168,0.164482,0.058403,0.322368,1.959907,0.028604,1.232998
171,(age_general),"(country_China, from_wuhan)",0.781883,0.097735,0.058403,0.074695,0.764259,-0.018015,0.975100
172,"(from_wuhan, age_general)",(gender_female),0.126341,0.413588,0.060787,0.481132,1.163314,0.008534,1.130177
173,"(age_general, gender_female)",(from_wuhan),0.327771,0.181168,0.060787,0.185455,1.023660,0.001405,1.005262
175,(age_general),"(from_wuhan, gender_female)",0.781883,0.082241,0.060787,0.077744,0.945321,-0.003516,0.995124
176,(from_wuhan),"(age_general, gender_female)",0.181168,0.327771,0.060787,0.335526,1.023660,0.001405,1.011671
177,(gender_female),"(from_wuhan, age_general)",0.413588,0.126341,0.060787,0.146974,1.163314,0.008534,1.024188
180,"(age_general, gender_male)",(from_wuhan),0.442193,0.181168,0.064362,0.145553,0.803412,-0.015749,0.958318
181,(from_wuhan),"(age_general, gender_male)",0.181168,0.442193,0.064362,0.355263,0.803412,-0.015749,0.865170
182,(age_general),"(from_wuhan, gender_male)",0.781883,0.096544,0.064362,0.082317,0.852642,-0.011123,0.984497
183,(gender_male),"(from_wuhan, age_general)",0.564958,0.126341,0.064362,0.113924,0.901720,-0.007015,0.985987
189,(recov),"(country_Singapore, location_Singapore)",0.172825,0.107271,0.070322,0.406897,3.793180,0.051783,1.505183
191,"(age_general, recov)",(location_Singapore),0.143027,0.107271,0.064362,0.450000,4.195000,0.049020,1.623144
193,(age_general),"(location_Singapore, recov)",0.781883,0.070322,0.064362,0.082317,1.170577,0.009379,1.013071
195,(recov),"(age_general, location_Singapore)",0.172825,0.096544,0.064362,0.372414,3.857471,0.047677,1.439574
198,"(age_general, recov)",(country_Singapore),0.143027,0.107271,0.064362,0.450000,4.195000,0.049020,1.623144
200,(age_general),"(country_Singapore, recov)",0.781883,0.070322,0.064362,0.082317,1.170577,0.009379,1.013071
201,(recov),"(country_Singapore, age_general)",0.172825,0.096544,0.064362,0.372414,3.857471,0.047677,1.439574
202,"(age_general, gender_female)",(recov),0.327771,0.172825,0.064362,0.196364,1.136201,0.007715,1.029290
203,"(age_general, recov)",(gender_female),0.143027,0.413588,0.064362,0.450000,1.088040,0.005208,1.066204
205,(age_general),"(gender_female, recov)",0.781883,0.076281,0.064362,0.082317,1.079125,0.004719,1.006577
206,(gender_female),"(age_general, recov)",0.413588,0.143027,0.064362,0.155620,1.088040,0.005208,1.014913
207,(recov),"(age_general, gender_female)",0.172825,0.327771,0.064362,0.372414,1.136201,0.007715,1.071134
210,"(age_general, gender_male)",(recov),0.442193,0.172825,0.078665,0.177898,1.029352,0.002243,1.006170
211,(recov),"(age_general, gender_male)",0.172825,0.442193,0.078665,0.455172,1.029352,0.002243,1.023823
212,(age_general),"(gender_male, recov)",0.781883,0.094160,0.078665,0.100610,1.068501,0.005043,1.007172
213,(gender_male),"(age_general, recov)",0.564958,0.143027,0.078665,0.139241,0.973523,-0.002139,0.995601
214,"(hosp_vis—sym_on_short, age_general)",(recov),0.287247,0.172825,0.066746,0.232365,1.344513,0.017103,1.077563
216,"(age_general, recov)",(hosp_vis—sym_on_short),0.143027,0.359952,0.066746,0.466667,1.296468,0.015263,1.200089
217,(hosp_vis—sym_on_short),"(age_general, recov)",0.359952,0.143027,0.066746,0.185430,1.296468,0.015263,1.052056
218,(age_general),"(hosp_vis—sym_on_short, recov)",0.781883,0.076281,0.066746,0.085366,1.119093,0.007103,1.009932
219,(recov),"(hosp_vis—sym_on_short, age_general)",0.172825,0.287247,0.066746,0.386207,1.344513,0.017103,1.161227
225,(age_general),"(location_Hong Kong, country_Hong Kong)",0.781883,0.094160,0.060787,0.077744,0.825660,-0.012835,0.982200
231,(gender_male),"(country_Singapore, location_Singapore)",0.564958,0.107271,0.063170,0.111814,1.042358,0.002567,1.005116
235,(hosp_vis—sym_on_short),"(country_Singapore, location_Singapore)",0.359952,0.107271,0.067938,0.188742,1.759492,0.029326,1.100426
242,(age_general),"(country_Singapore, location_Singapore)",0.781883,0.107271,0.096544,0.123476,1.151067,0.012670,1.018488
245,"(age_general, gender_male)",(location_Singapore),0.442193,0.107271,0.058403,0.132075,1.231237,0.010969,1.028580
247,(age_general),"(location_Singapore, gender_male)",0.781883,0.063170,0.058403,0.074695,1.182438,0.009011,1.012455
249,(gender_male),"(age_general, location_Singapore)",0.564958,0.096544,0.058403,0.103376,1.070766,0.003860,1.007620
250,"(hosp_vis—sym_on_short, age_general)",(location_Singapore),0.287247,0.107271,0.064362,0.224066,2.088797,0.033549,1.150523
253,(hosp_vis—sym_on_short),"(age_general, location_Singapore)",0.359952,0.096544,0.064362,0.178808,1.852097,0.029611,1.100177
254,(age_general),"(hosp_vis—sym_on_short, location_Singapore)",0.781883,0.067938,0.064362,0.082317,1.211650,0.011243,1.015669
260,(gender_female),"(location_South Korea, country_South Korea)",0.413588,0.107271,0.057211,0.138329,1.289529,0.012845,1.036044
262,"(location_South Korea, country_South Korea)",(gender_male),0.107271,0.564958,0.050060,0.466667,0.826020,-0.010544,0.815703
265,(location_South Korea),"(gender_male, country_South Korea)",0.107271,0.051251,0.050060,0.466667,9.105426,0.044562,1.778903
266,(country_South Korea),"(location_South Korea, gender_male)",0.109654,0.050060,0.050060,0.456522,9.119565,0.044570,1.747890
267,(gender_male),"(location_South Korea, country_South Korea)",0.564958,0.107271,0.050060,0.088608,0.826020,-0.010544,0.979523
272,(age_general),"(location_South Korea, country_South Korea)",0.781883,0.107271,0.091776,0.117378,1.094224,0.007903,1.011452
276,"(age_general, gender_female)",(location_South Korea),0.327771,0.107271,0.050060,0.152727,1.423758,0.014899,1.053651
277,(location_South Korea),"(age_general, gender_female)",0.107271,0.327771,0.050060,0.466667,1.423758,0.014899,1.260429
278,(age_general),"(location_South Korea, gender_female)",0.781883,0.057211,0.050060,0.064024,1.119093,0.005327,1.007279
279,(gender_female),"(location_South Korea, age_general)",0.413588,0.091776,0.050060,0.121037,1.318837,0.012102,1.033291
280,"(country_China, age_general)",(gender_female),0.164482,0.413588,0.060787,0.369565,0.893560,-0.007241,0.930171
282,"(age_general, gender_female)",(country_China),0.327771,0.221692,0.060787,0.185455,0.836540,-0.011878,0.955511
283,(country_China),"(age_general, gender_female)",0.221692,0.327771,0.060787,0.274194,0.836540,-0.011878,0.926182
284,(age_general),"(country_China, gender_female)",0.781883,0.083433,0.060787,0.077744,0.931816,-0.004448,0.993832
285,(gender_female),"(country_China, age_general)",0.413588,0.164482,0.060787,0.146974,0.893560,-0.007241,0.979476
288,"(age_general, gender_male)",(country_China),0.442193,0.221692,0.103695,0.234501,1.057778,0.005664,1.016733
289,(country_China),"(age_general, gender_male)",0.221692,0.442193,0.103695,0.467742,1.057778,0.005664,1.048001
290,(age_general),"(country_China, gender_male)",0.781883,0.138260,0.103695,0.132622,0.959223,-0.004408,0.993500
291,(gender_male),"(country_China, age_general)",0.564958,0.164482,0.103695,0.183544,1.115896,0.010770,1.023348
292,"(country_Japan, age_general)",(gender_female),0.164482,0.413588,0.058403,0.355072,0.858518,-0.009625,0.909269
294,"(age_general, gender_female)",(country_Japan),0.327771,0.221692,0.058403,0.178182,0.803734,-0.014262,0.947056
295,(country_Japan),"(age_general, gender_female)",0.221692,0.327771,0.058403,0.263441,0.803734,-0.014262,0.912661
296,(age_general),"(country_Japan, gender_female)",0.781883,0.076281,0.058403,0.074695,0.979206,-0.001240,0.998286
297,(gender_female),"(country_Japan, age_general)",0.413588,0.164482,0.058403,0.141210,0.858518,-0.009625,0.972902
300,"(hosp_vis—sym_on_short, gender_male)",(country_Japan),0.220501,0.221692,0.083433,0.378378,1.706771,0.034549,1.252060
301,(country_Japan),"(hosp_vis—sym_on_short, gender_male)",0.221692,0.220501,0.083433,0.376344,1.706771,0.034549,1.249887
302,(hosp_vis—sym_on_short),"(country_Japan, gender_male)",0.359952,0.144219,0.083433,0.231788,1.607192,0.031521,1.113990
303,(gender_male),"(country_Japan, hosp_vis—sym_on_short)",0.564958,0.127533,0.083433,0.147679,1.157972,0.011382,1.023637
306,"(age_general, gender_male)",(country_Japan),0.442193,0.221692,0.106079,0.239892,1.082094,0.008048,1.023944
307,(country_Japan),"(age_general, gender_male)",0.221692,0.442193,0.106079,0.478495,1.082094,0.008048,1.069609
308,(age_general),"(country_Japan, gender_male)",0.781883,0.144219,0.106079,0.135671,0.940725,-0.006684,0.990110
309,(gender_male),"(country_Japan, age_general)",0.564958,0.164482,0.106079,0.187764,1.141549,0.013153,1.028664
312,"(hosp_vis—sym_on_short, age_general)",(country_Japan),0.287247,0.221692,0.098927,0.344398,1.553496,0.035247,1.187165
313,(country_Japan),"(hosp_vis—sym_on_short, age_general)",0.221692,0.287247,0.098927,0.446237,1.553496,0.035247,1.287108
314,(hosp_vis—sym_on_short),"(country_Japan, age_general)",0.359952,0.164482,0.098927,0.274834,1.670914,0.039722,1.152176
315,(age_general),"(country_Japan, hosp_vis—sym_on_short)",0.781883,0.127533,0.098927,0.126524,0.992093,-0.000788,0.998846
318,"(age_general, gender_male)",(country_Singapore),0.442193,0.107271,0.058403,0.132075,1.231237,0.010969,1.028580